ktor:
  deployment:
    port: 8080
  application:
    modules:
      - pet.articles.web.config.ApplicationConfigKt.module

api:
  paths:
    users: "/api/users"
    articles: "/api/articles"
    reviews: "/api/reviews"
    registration: "/api/registration"
    auth: "/api/auth"